### ISSUE TITLE
Network Error when clicking Generate

### ISSUE THREAD

**Issue by oFthiSUSer** [cameronking4/sketch2app#2]
I get a "Network Error" error when I click Generate Code Sandbox
![Screenshot_2024-04-03-22-54-38-299_com android chrome-edit](https://github.com/cameronking4/sketch2app/assets/165943080/66922b2d-3114-42c7-90f5-8acd608cea40)

**Comment by cameronking4** [comment]
Restored API KEY, hit limit 24 hours sorry about that.
